version: '3'

services:
  nuxt:
    build: .
    ports:
      - ${VIRTUAL_PORT}:3000
    restart: always
    env_file: .env
    environment:
      NODE_ENV: production
    command: sh -c 'yarn install && yarn build && yarn start'
    volumes:
      - .:/app:rw
    networks:
      - proxy

networks:
  proxy:
    external:
      name: ${NETWORK_PROXY_NAME}
