version: '3'

services:
  nginx:
    image: nginx:1.15.2-alpine
    ports:
      - ${VIRTUAL_PORT}:80
    restart: always
    env_file: .env
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - nuxt
    networks:
      - ${NETWORK_PROXY_NAME}
      - default

  nuxt:
    build: ./nuxt
    expose:
      - 3000
    restart: always
    env_file: .env
    environment:
      NODE_ENV: production
    command: sh -c 'yarn install && yarn build && yarn start'
    volumes:
      - ./nuxt:/app:rw
    networks:
      - default

networks:
  ${NETWORK_PROXY_NAME}:
    external: true
  default:
