version: '3'

services:
  nuxt:
    environment:
      NODE_ENV: development
    command: sh -c 'yarn install && yarn dev'
    volumes:
      - sync:/app:nocopy

volumes:
  sync:
    external:
      name: ${COMPOSE_PROJECT_NAME}-sync
